

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # You can change this to your preferred Java version
          distribution: 'temurin'

      - name: Build Spring Boot App
        run: |
          
          ./mvnw clean package -DskipTests  # Or use ./gradlew for Gradle

      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: YOUR_BACKEND_APP_NAME  # Replace with your backend app name on Azure
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: ./backend/target/*.jar

  